// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

// Injectors from wire.go:

//func InitializeTraceMessage() TraceMessage {
//	traceMessage := NewTraceMessage()
//	return traceMessage
//}
